[package]
name = "patriots8800/easytype"
description = "Custom type-checker for custom objects and classes"
version = "2.0.2"
license = "MIT"
realm = "shared"
registry = "https://github.com/Green-Screen/wally-index"
repository = "https://github.com/Green-Screen/EasyType"
[dependencies]